import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  /*title: "Welcome to Laser247",
  description: "Generated by create next app",*/
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        
        <link rel="icon" href="images/g-favicon.png" type="image/png"></link>
	    	<link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet" />
		    <link rel="stylesheet" href="css/all.css"  />
        <link rel="stylesheet" href="css/style.css" type="text/css" />
        
        <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css" />
        <link rel="stylesheet" href="css/frontend.min.css?ver=3.24.4" type="text/css" />
		    <link rel="stylesheet" href="css/owl.carousel.min.css" />
		
        <meta name="description" content="Laser247 is the world's largest gaming website. More than 3500+ sports games available daily on Laser247.online website. Get the best odds, instant deposit and withdrawal. 24/7 customer support and referral bonuses. Get Laser247 Login ID today's." />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
